name: "sbt ci build"
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, ready_for_review, reopened ]
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: adopt@1.11
      - name: Run tests & stage files
        run: sbtn test
